### ISSUE TITLE
Unhandled exception takes down node-red when server is not reachable

### ISSUE THREAD

**Issue by clough42** [derBroBro/node-red-contrib-thingspeak#2]
My internet provider went down this morning, so ThingSpeak was not reachable, and node-red died with an unhandled exception trying to connect.

I believe you just need to add an .on('error') handler to the https.get(...) to catch these errors and prevent it from taking down node-red.

**Comment by derBroBro** [comment]
Hi, 
thank you the hint. If you fix it and send an merge request I am happy to integrate it. :-)
Best Malte

**Comment by clough42** [comment]
I'll take a look when I get the chance.  Maybe this weekend.  I have several projects going at once.  :)

**Comment by clough42** [comment]
@derBroBro Pull request submitted.
